[package]
name = "acv"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Elliott Weix"]
license = "Unlicense"
description = "Academic CV for the natural sciences."
repository = "https://github.com/eweix/acv"
keywords = ["cv"]
categories = ["cv"]
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
